name: Merge to Master on Push

on:
  push:
    branches:
      - develop

jobs:
  merge_to_master:
    runs-on: ubuntu-latest

    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Merge to master
        run: |
          git config user.name "AW"
          git config user.email "djwotmd@gmail.com"
          git clone https://github.com/awjae/electron_study.git
          git remote update
          git checkout main
          git merge -Xtheirs --allow-unrelated-histories develop -m "Merge develop into master"
          git push origin main
